=== sixrobin/Club-Dev_Datas/[CODE SOURCE]/CLUB-DEV_DATAS/Assets/03_XML/Datafiles/WeaponDefinitions.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:element name="WeaponDefinitions">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="WeaponDefinition" minOccurs="0" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="Rate" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="ReloadDuration" type="xs:float" minOccurs="1" maxOccurs="1"/>
                     <xs:element name="MagazineCapacity" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
                     <xs:element name="Behaviour" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="Laser" minOccurs="0" maxOccurs="1">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="LaserPrefabId" type="xs:token" minOccurs="1" maxOccurs="1"/>
                                       <xs:element name="Duration" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                 </xs:complexType>
                              </xs:element>
                              <xs:element name="Gun" minOccurs="0" maxOccurs="1">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="BulletPrefabId" type="xs:token" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                 </xs:complexType>
                              </xs:element>
                              <xs:element name="Shotgun" minOccurs="0" maxOccurs="1">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="BulletPrefabId" type="xs:token" minOccurs="1" maxOccurs="1"/>
                                       <xs:element name="Angle" type="xs:float" minOccurs="1" maxOccurs="1"/>
                                       <xs:element name="Count" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:token" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
</xs:schema>

=== sixrobin/Club-Dev_Datas/[CODE SOURCE]/CLUB-DEV_DATAS/Assets/03_XML/Datafiles/WeaponDefinitions.xml
<WeaponDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="WeaponDefinitions.xsd">

   <WeaponDefinition Id="BasicGun">
      <Rate>0.2</Rate>
      <ReloadDuration>1</ReloadDuration>
      <MagazineCapacity>10</MagazineCapacity>
      <Behaviour>
         <Gun>
            <BulletPrefabId>Bullet</BulletPrefabId>
         </Gun>
      </Behaviour>
   </WeaponDefinition>

   <WeaponDefinition Id="Uzi">
      <Rate>0.1</Rate>
      <ReloadDuration>0.5</ReloadDuration>
      <MagazineCapacity>500</MagazineCapacity>
      <Behaviour>
         <Gun>
            <BulletPrefabId>UziBullet</BulletPrefabId>
         </Gun>
      </Behaviour>
   </WeaponDefinition>

   <WeaponDefinition Id="BasicShotgun">
      <Rate>0.3</Rate>
      <ReloadDuration>0.5</ReloadDuration>
      <MagazineCapacity>5</MagazineCapacity>
      <Behaviour>
         <Shotgun>
            <BulletPrefabId>Bullet</BulletPrefabId>
            <Angle>25</Angle>
            <Count>4</Count>
         </Shotgun>
      </Behaviour>
   </WeaponDefinition>

   <WeaponDefinition Id="EpicShotgun">
      <Rate>0.1</Rate>
      <ReloadDuration>0.5</ReloadDuration>
      <MagazineCapacity>10</MagazineCapacity>
      <Behaviour>
         <Shotgun>
            <BulletPrefabId>Bullet</BulletPrefabId>
            <Angle>30</Angle>
            <Count>6</Count>
         </Shotgun>
      </Behaviour>
   </WeaponDefinition>

   <WeaponDefinition Id="Laser">
      <Rate>0.5</Rate>
      <ReloadDuration>1</ReloadDuration>
      <Behaviour>
         <Laser>
            <LaserPrefabId>Laser</LaserPrefabId>
            <Duration>2</Duration>
         </Laser>
      </Behaviour>
   </WeaponDefinition>
   
</WeaponDefinitions>
